/*You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''*/
package org.StringDiff;

import java.util.HashSet;


public class MainClass {

	static Character spotdiff(String str1, String str2)
	{
		HashSet<Character> hs = new HashSet<Character>();
		for(int i=0;i<str1.length();i++)
			hs.add(str1.charAt(i));
		for(int i=0;i<str2.length();i++)
			if(!hs.contains(str2.charAt(i))) 
				return str2.charAt(i);
		return 0;
		
	}
	public static void main(String[] args) {
		String s = "idae", t = "idea";
		System.out.println(spotdiff(s, t));
	}
	
	
}
